apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/ibrahim-shaaban-hussein/openshift-hybrid-gitops'
    targetRevision: HEAD
    path: argo-cd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

